# Tracker config

actor: '/home/wzielonka/PycharmProjects/metrical-tracker/input/duda'
save_folder: '/work/wzielonka/projects/metrical-tracker/output/'
optimize_shape: true
keyframes: [ 0, 1, 2, 3, 4 ]
sampling: [[0.5, 200], [1.0, 60], [2.0, 60]]